### PR TITLE
 Airbnb WebPage clone

### PR DESCRIPTION
**Pull request by Mrjoy832**
## 🛠️ Fixes Issue

Closes #
- #198 

## 👨‍💻 Changes proposed
- 1. Added Structured code in a separated folder.
-  2. All images are attached into the folder , Tech Stack Used-> HTML, CSS, JS

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@Rayman-Sodhi , @whiteHatpro , kindly check the PR of issue #198

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
@Mrjoy832  Change Folder name `WebPage Clone- 'Airbnb'` to `Airbnb Clone`

and add deployed link to `README.md`

**Comment by Mrjoy832** [comment]
> @Mrjoy832 Change Folder name `WebPage Clone- 'Airbnb'` to `Airbnb Clone`
> 
> and add deployed link to `README.md`

Updated deployed link and name

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by Kushal997-das** [comment]
@gurjeetsinghvirdee Remove the tag as it already exits in this project .

https://github.com/Rayman-Sodhi/Clone-IT/pull/220

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee Remove the tag as it already exits in this project .
> 
> #220

done

**Comment by Mrjoy832** [comment]
> @gurjeetsinghvirdee Remove the tag as it already exits in this project .
> 
> #220

Where?? I cannot see it in main branch

**Comment by Kushal997-das** [comment]
> > @gurjeetsinghvirdee Remove the tag as it already exits in this project .
> > #220
> 
> Where?? I cannot see it in main branch

https://github.com/Rayman-Sodhi/Clone-IT/pull/220

**Pull request merged**
