### PR TITLE
Linked Clones

### LINKED ISSUE #378: Add all clones alphabetically in readme
In total there are 59 clones folders . If there are others too Count and add in readme

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
## 🛠️ Fixes Issue

Closes #378 

## 👨‍💻 Changes proposed

- Clones added as cards in the Index file
- Background image fixed 
- Some logos have no background or small image, So I put **`background-color: white`** as it looks good you can check in screenshots also
- Clones linked with **`Search-Bar`**
- Deleted 3 Projects as they are copied content, These projects were deleted:
1) Twitter Clone
2) Food Panda Clone
3) Amazon Prime Clone
- Fixed some issues in the **` README.md`** file
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I will Fix Readme in that next PR that is pending for Amazon Deployment, Actually, there are many projects that were not been deployed yet so, I will deploy all projects and update Readme in the next PR

## 📷 Screenshots

Screenshot (889)

Screenshot (891)

Screenshot (892)

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Don't Merge now have to add more projects

**Comment by Rayman-Sodhi** [comment]
sace
please check the table layout

**Comment by gurjeetsinghvirdee** [comment]
> sace please check the table layout

krta hu phle link toh kru

**Comment by gurjeetsinghvirdee** [comment]
Screenshot (883)

hogya thk par merge na kre abhi, lot of things to fix in index files

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi Review PR

**Pull request merged**
