### PR TITLE
Added Rapido Bike Taxi Website Clone 

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR of the issue Rapido Bike Taxi Website Clone #391..Please review it sir

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 2 commits ahead, 15 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by eswarbhageerath** [comment]
Fetched and merged sir.. please review my PR

**Comment by gurjeetsinghvirdee** [comment]
4 commits behind @eswarbhageerath

**Comment by eswarbhageerath** [comment]
Done my fetch and Merge sir

**Comment by eswarbhageerath** [comment]
@gurjeetsinghvirdee I have deployed the site sir....

https://eswarbhageerath.github.io/Rapido-Website-Clone/

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
