### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by utkarsh006**
- SEE CHANGES [HERE](https://github.com/utkarsh006/Clone-IT/blob/Readme_Updation/README.md)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@gurjeetsinghvirdee Kindly Review.

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
I think you removed GSSoC & SWOC from open source, please re-attach this

**Comment by utkarsh006** [comment]
@gurjeetsinghvirdee Kindly Review now.

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM✨

**Comment by gurjeetsinghvirdee** [comment]
Closes #712

**Pull request merged**
