### PR TITLE
#184 NYKAA Clone created

### LINKED ISSUE #184: Create Nykaa Clone
### Is your feature request related to a problem? Please describe.

Yes, since I am contribution a website clone

### Describe the solution you'd like.

I will use HTML, CSS(Bootstrap Framework) and JS(Node JS Framework)

### Describe alternatives you've considered.

-

### Add any other context or screenshots about the feature request here.

image

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
## 🛠️ Fixes Issue

Closes #184 

## 👨‍💻 Changes proposed
- Create NYKAA Clone
- Link it to index.html
- Update the README.md

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Nothing specific

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Can you share deployed link here @Kumar-laxmi

**Comment by Kumar-laxmi** [comment]
But their isn't any deployement link

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee  But their isn't any deployement link

Bro deploy it

**Comment by Kumar-laxmi** [comment]
@gurjeetsinghvirdee  Here is the deployment link:

https://clone-it-opensource.vercel.app/NYKAA-CLONE/index.html

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
Code copied from `https://github.com/Ankit-Mishra07/Nykaa` 
you want to say something @Kumar-laxmi 


@Rayman-Sodhi @whiteHatpro

**Pull request merged**
