### PR TITLE
Myntra Clone using React Js

### LINKED ISSUE #258: [New Issue]: Myntra website clone
### Description

Description of the project here

Clone of the Myntra website made using React Js.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by Debdeep1**
## 🛠️ Fixes Issue

Closes #258  Myntra Website Clone

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

This is a clone of Myntra's UI using React Js. All the dependencies have been installed in the .json file.

## 📷 Screenshots
WhatsApp Image 2022-04-04 at 16 52 12

### CODE REVIEW

**Comment by Debdeep1** [comment]
Myntra UI clone using React added.

**Comment by Debdeep1** [comment]
Myntra UI clone using React added.

**Comment by gurjeetsinghvirdee** [comment]
Bro can you deploy your project @Debdeep1

**Comment by Debdeep1** [comment]
Sir, I have uploaded the deploy link in Readme file.

**Comment by Debdeep1** [comment]
https://d1-myntra-clone.netlify.app/

**Comment by gurjeetsinghvirdee** [comment]
> https://d1-myntra-clone.netlify.app/

Don't call me sir😅

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
LGTM💜

**Pull request merged**
