### PR TITLE
Added MICROSOFT CLONE 

### PR DESCRIPTION
**Pull request by 19arnab190201**
Added a microsoft clone in the library and updated the readme.md file with links and added a new microsoft card in the main page.

### SCREENSHOT OF MAIN PAGE 
Clone-IT

### SCREENSHOT OF MICROSOFT CLONE
Hello, world!

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
Great Job!

**Comment by 19arnab190201** [comment]
> Great Job!

Thank You

**Comment by gurjeetsinghvirdee** [comment]
hey @Rayman-Sodhi changing a level coz it was too good

**Comment by Rayman-Sodhi** [comment]
okay 👍

**Pull request merged**
