### PR TITLE
Removed extra Images

### PR DESCRIPTION
**Pull request by VaibhavUpreti**
## 🛠️ Fixes Issue #364 

Closes #

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I have removed most of the images that were used in assets folder ....(just the ones that are displayed in the card of the clone-it website)

### CODE REVIEW

**Comment by VaibhavUpreti** [comment]
Also one of my site was missing a favicon and there were some CSS issues .... so I cleared them with this PR

**Comment by VaibhavUpreti** [comment]
Could you guide me regarding this Imgbot..... do I just have to add it... cause I took the subscription

**Comment by VaibhavUpreti** [comment]
I found the configurations 
 https://imgbot.net/docs/#configuration
 
 Ig would have to add a .imgbotconfig json file

**Comment by VaibhavUpreti** [comment]
Status Update - Imgbot is up. & running ..... would have to give it some time though ... it is going through all my repositories one by one

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I did these changes but github is giving me this imgbot just for 10 days and idk much about it...

bro apply for GitHub student developer pack

**Comment by VaibhavUpreti** [comment]
> > @gurjeetsinghvirdee I did these changes but github is giving me this imgbot just for 10 days and idk much about it...
> 
> bro apply for GitHub student developer pack

I have the pack ... and I have taken the bot
 but href-



> I found the configurations https://imgbot.net/docs/#configuration
> 
> Ig would have to add a .imgbotconfig json file

**Comment by gurjeetsinghvirdee** [comment]
> Status Update - Imgbot is up. & running ..... would have to give it some time though ... it is going through all my repositories one by one

no issue it will take a time

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
