### PR TITLE
Linktree added in readme

### PR DESCRIPTION
**Pull request by harshita214**
#31 readme updated

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
hey harshita ..can you generalize the link tree . This doesn't look like a clone but a linktree about ur own details.U can just put links for insta and all not ur own profile

**Comment by harshita214** [comment]
The link which is in the readme is an example of a link tree, the code which I have uploaded doesn't have my links. They are only available here for demo purposes.

**Comment by Rayman-Sodhi** [comment]
oh then using the code try to create a demo linktree and add that link in readme

**Comment by harshita214** [comment]
Okay

**Review by harshita214 — COMMENTED** [review]
Changed the link, removed all my links now only there is a pic that is a reference only

**Comment by Rayman-Sodhi** [comment]
This branch is 2 commits ahead, 9 commits behind Rayman-Sodhi:main.

**Comment by Rayman-Sodhi** [comment]
kindly perform a git pull and then make the pr

**Comment by harshita214** [comment]
Sure , done

**Comment by harshita214** [comment]
Also can you merge my code also as its not merged yet #31

**Pull request merged**
