### PR TITLE
Add a Twitter-Homepage Clone

### LINKED ISSUE #271: Twitter Clone
### Description

Description
Building a Twitter Clone web application

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by le11evan**
## 🛠️ Fixes Issue #271 

Closes #271 

## 👨‍💻 Changes proposed

1. Made a Twitter Homepage Clone using react.js. 

## ✔️ Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

This Twitter Homepage clone was made using react.js. I'm pretty new to pull-requests, so I'm not sure if this is what you fully wanted. This pull request just adds the folder for my clone. I wasn't sure if I was also supposed to edit the actual website and add a new Twitter section. But yeah. I hope this works. 

## 📷 Screenshots
image

image

image

image

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
@le11evan hey you are GSSoC' 22 contributor?

**Comment by le11evan** [comment]
> @le11evan hey you are GSSoC' 22 contributor?

Hi @Akshata-Gunapache, I am not, how do I register to be one? I'm actually a student at a university, and one of our assignments is to find an open source project to contribute to, and merge a pull request. I found this repo on a website, so I decided to work on it, it seemed interesting! It would help me out if I can contribute somehow, but if it's only for certain people, then its alright. Thanks !

**Comment by gurjeetsinghvirdee** [comment]
Not a issue you contribute as well as open source programmer. 

By the way if you have deployed link then add here 
Bcoz I have to add links on json files

**Comment by le11evan** [comment]
> Not a issue you contribute as well as open source programmer.
> 
> By the way if you have deployed link then add here Bcoz I have to add links on json files

Oh thank you so much! Here is the link to the deployed site: https://le11evan.github.io/twitter-clone/

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM 💜

**Pull request merged**
