### PR TITLE
Gmail UI Clone 

### PR DESCRIPTION
**Pull request by Mrjoy832**
## 🛠️ Fixes Issue
Closes #
- #106 

## 👨‍💻 Changes proposed
 >   1. Added folder named Gmail UI Clone<br>
       2. In the folder added HTML , CSS code used to clone Gmail UI.

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
All the codes are crystal clear, comments related to every objects are added to make it simple to understand . 😊

## 📷 Screenshots
**Image of UI**
image
**Video Demo**

https://user-images.githubusercontent.com/77873383/159171936-09807ba4-3fc4-4b1a-afa3-95b04e4a54bc.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Will be added readme File soon

**Comment by Mrjoy832** [comment]
@Rayman-Sodhi , Please check it.

**Comment by gurjeetsinghvirdee** [comment]
> Will be added readme File soon

not an issue I will add it just send me a link

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM💜

**Pull request merged**
