### PR TITLE
Create LICENSE.md

### LINKED ISSUE #111: Adding License

### PR DESCRIPTION
**Pull request by Ash-KODES**
FIXES #111

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 1 commit ahead, 12 commits behind Rayman-Sodhi:main.

**Comment by Ash-KODES** [comment]
#121

**Comment by Ash-KODES** [comment]
> This branch is 1 commit ahead, 12 commits behind Rayman-Sodhi:main.

Done!please review

**Comment by gurjeetsinghvirdee** [comment]
Closing this one because you created a new PR

**Pull request closed without merging**
