### PR TITLE
Add scroll to top button on main website

### LINKED ISSUE #97: Add scroll to top button to main website
## Fixes
- Add Scroll to top button on the main website
- Enable smooth scrolling of page when the button is pressed

### Comments
I am a GSSoC '22 participant. 
Please assign this issue to me so that I can work on it.

### PR DESCRIPTION
**Pull request by aditi-singh-442**
## 🛠️ Fixes Issue

Closes #97 

## 👨‍💻 Changes proposed
- Added a scroll to top button on main website
- The button is visible when the page is scrolled down
- Offers a smooth scrolling back up to the top

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Screenshot from 2022-03-21 11-34-58
Screenshot from 2022-03-21 11-48-00

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
hey, can you make a video? like how it's working

**Comment by aditi-singh-442** [comment]
yes sure.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
fetch your branch 6 commits behind from main branch

**Comment by aditi-singh-442** [comment]
Here's a video demonstrating the feature

[2022-03-21_12-13-06.zip](https://github.com/Rayman-Sodhi/Clone-IT/files/8313564/2022-03-21_12-13-06.zip)

**Comment by gurjeetsinghvirdee** [comment]
> fetch your branch 6 commits behind from the main branch

@aditi-singh-442

**Comment by Rayman-Sodhi** [comment]
This branch is 1 commit ahead, 13 commits behind Rayman-Sodhi:main.

**Comment by aditi-singh-442** [comment]
I have fetched the commits from main. Please review once.

**Pull request merged**
