### PR TITLE
Added Girlscript Summer Of Code(GSSoC) Website Clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This is the PR for the issue Girlscript Summer Of Code(GSSoC) Website Clone #394
Kindly Review it
Thank you Sir

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 2 commits ahead, 15 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by SupriyaGembali** [comment]
I have updated the repo sir,I done Fetch and Merge . Please review my PR sir

**Comment by gurjeetsinghvirdee** [comment]
Can you deploy this project @SupriyaGembali

**Comment by SupriyaGembali** [comment]
https://supriyagembali.github.io/Girl-Script-Summer-of-code-website-clone/ 
This is the hosted link sir @gurjeetsinghvirdee

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
Code copied from the original website


Screenshot (894)

@Rayman-Sodhi

**Pull request merged**
