### PR TITLE
Added Docker Clone

### LINKED ISSUE #579: Docker Clone
### Description

Would like to work on Docker Clone
Please assign it to me

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by hariketsheth**
## 🛠️ Fixes Issue
Fixes #579 

## 👨‍💻 Changes proposed
Added Clone for Docker

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

image

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is [2 commits ahead](https://github.com/hariketsheth/Clone-IT/compare/Rayman-Sodhi:main...main), [10 commits behind](https://github.com/hariketsheth/Clone-IT/compare/main...Rayman-Sodhi:main) Rayman-Sodhi:main.

**Comment by hariketsheth** [comment]
@Rayman-Sodhi  Done !

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Do you make this project? please attach a demo video with your code

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee  Review 
https://user-images.githubusercontent.com/72455881/170650132-1ebda4c6-e329-4ab3-b968-68f8b61588cf.mp4

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee Can I request for level 3 on this ?
Since I had tried to add my best to make it as close as Actual Docker Website

**Pull request merged**
