### PR TITLE
Amazon Clone created

### LINKED ISSUE #46: Add AMAZON clone

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
## 🛠️ Fixes Issue

Closes #46 

## 👨‍💻 Changes proposed
- Create an Amazon clone
- Link it to index.html
- Update README.md: Include official as well as un-official link to website
- Worked a little on #150 

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Nothing specific

## 📷 Screenshots
image
image
image

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
Hi you have to add the clone in main website alphabetically

**Comment by Rayman-Sodhi** [comment]
It will come as number 1 ,before apple clone

**Comment by Kumar-laxmi** [comment]
Ohk

**Comment by Kumar-laxmi** [comment]
@Rayman-Sodhi @gurjeetsinghvirdee Hey I have reordered, please do check it

image

**Comment by gurjeetsinghvirdee** [comment]
> @Rayman-Sodhi @gurjeetsinghvirdee Hey I have reordered, please do check it
> 
> image
> 

Maybe your branch some commits behind coz I rearranged today 12 am

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
LGTM

**Comment by gurjeetsinghvirdee** [comment]
@Kumar-laxmi code copied from this repo `https://github.com/aaroncodehub/amazon-clone-react-redux`

@Rayman-Sodhi what to do now?

**Pull request merged**
