### PR TITLE
Correct offer section and categories section in kfc clone

### PR DESCRIPTION
**Pull request by jalauk**
# Modification as per the original KFC webpage

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
can u change the font as in main website and also add one more offfer so carousel can work

**Comment by Rayman-Sodhi** [comment]
laso compare the height of order section with main website

**Comment by jalauk** [comment]
@Rayman-Sodhi font used in the main website is "National 2 Condensed" which is not available in google font, so I used "open sans condensed" as an alternative. Can you suggest an alternative?

**Comment by jalauk** [comment]
@Rayman-Sodhi I have made changes but maybe a licence is needed for commercial use "National 2 Condensed" font.
If there are some errors pls let me know.

**Comment by Rayman-Sodhi** [comment]
Looks Great!

**Comment by jalauk** [comment]
@Rayman-Sodhi pls update the mark on score sheet

**Pull request merged**
