### PR TITLE
Update README.md, add all projects

### LINKED ISSUE #445: Add all clones in the Readme file in the available clones section .
Arrange all the clones alphabetically with proper links . This image shows the table where all clones have to be added
Screenshot 2022-05-08 002515

### PR DESCRIPTION
**Pull request by aaryahjolia**
## 🛠️ Fixes Issue

Closes #445 

## 👨‍💻 Changes proposed

Added all the projects to the table where links were there of the cloned website

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

GSSoC Contributor

## 📷 Screenshots

image

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
have u added all the projects alphabetically

**Comment by aaryahjolia** [comment]
Okay will do it tomorrow !

**Comment by aaryahjolia** [comment]
@Rayman-Sodhi Please review

**Comment by Rayman-Sodhi** [comment]
it shows 61 clones in main website

**Comment by aaryahjolia** [comment]
Many clones are not linked properly in main website, so unable to get their link.
Example : Amazon clone, Freshworks clone, Google shopping website clone, etc.

**Comment by Rayman-Sodhi** [comment]
you can add their names and the links  can be updated afterwards

**Comment by aaryahjolia** [comment]
@Rayman-Sodhi Resolved! Please Check now

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
