### PR TITLE
Changes in flipkart clone

### PR DESCRIPTION
**Pull request by kalashvasaniya**
Improve flipkart clone!

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
is this done @gurjeetsinghvirdee ?

**Comment by gurjeetsinghvirdee** [comment]
> is this done @gurjeetsinghvirdee ?
> 

Maybe 

Can u add screenshot here @kalashvasaniya what you changed

**Comment by kalashvasaniya** [comment]
> > is this done @gurjeetsinghvirdee ?
> 
> Maybe
> 
> Can u add screenshot here @kalashvasaniya what you changed

I have change Minor-Minor very changes like border-radius, that search is not at proper loaction so i located at right places then some padding & margin many change but minor.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
@kalashvasaniya 

This branch is 1 commit ahead, 39 commits behind Rayman-Sodhi/Clone-IT: main.

**Pull request merged**
