### PR TITLE
2048 game 

### LINKED ISSUE #224: Add 2048 game
2048 game using React Js

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
## 🛠️ Fixes Issue

Closes #224 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I forgot to record it  was mobile responsive also can you change the label Level 2 to 3 or 4

## 📷 Screenshots / Videos 

https://user-images.githubusercontent.com/73753957/161246119-d708db27-f2d5-443c-9d70-a2b153e489b4.mp4

Screenshot (768)

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
is this a clone of some game?

**Comment by gurjeetsinghvirdee** [comment]
> is this a clone of some game?

ye Kaise merge hogya sorry 


2048 game clone

**Comment by gurjeetsinghvirdee** [comment]
you can check on play store @Rayman-Sodhi

**Comment by sampavaranasi** [comment]
@Rayman-Sodhi contributor can add levels( level 3 ) ,  can merge prs?

**Pull request merged**
