### PR TITLE
    Car dealer ship website "costal saves" clone

### LINKED ISSUE #451: Car dealer ship website "costal saves" clone
### Description

costal promise is car dealership website.
image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## 🛠️ Fixes Issue

Closes #451 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by gurjeetsinghvirdee — COMMENTED** [review]
Deploy this website @DragonUncaged

**Comment by DragonUncaged** [comment]
> Deploy this project @DragonUncaged

https://Car-Dealer.dragonuncaged.repl.co

**Comment by Rayman-Sodhi** [comment]
This branch is 1 commit ahead, 16 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by DragonUncaged** [comment]
> This branch is 1 commit ahead, 16 commits behind Rayman-Sodhi/Clone-IT:main.

done!!

**Pull request merged**
