### PR TITLE
Add a Udemy Clone

### LINKED ISSUE #490: [New Issue]: Add a Udemy clone
### Description

I would like to add a clone of Udemy to this project. I will build the project using React JS. Please do assign me this issue!

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by mahiiverse1**
## 🛠️ Fixes Issue

Closes #490 

## 👨‍💻 Changes proposed

1. Made a Udemy Clone using react js.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

[Udemy Clone Deployed Website](https://udemy-clone-mahiiverse1.netlify.app/)

## 📷 Screenshots

Screenshot 2022-05-24 at 2 25 45 PM
Screenshot 2022-05-24 at 2 25 58 PM
Screenshot 2022-05-24 at 2 26 05 PM
Screenshot 2022-05-24 at 2 26 13 PM

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is [6 commits ahead](https://github.com/mahiiverse1/Clone-IT/compare/Rayman-Sodhi:main...main), [4 commits behind](https://github.com/mahiiverse1/Clone-IT/compare/main...Rayman-Sodhi:main) Rayman-Sodhi:main.

**Comment by mahiiverse1** [comment]
updated the repo just now @Rayman-Sodhi

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Remove `package-lock.json` file

**Comment by mahiiverse1** [comment]
@gurjeetsinghvirdee done

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
