### PR TITLE
Behance Clone

### LINKED ISSUE #132: Behance clone
Hello, I want to clone this site, GSSOC'22
https://www.behance.net/

### LINKED ISSUE #361: Add Behance Clone
### Description

Behance Clone with react js

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
## 🛠️ Fixes Issue

Closes #361 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Not Deployed tried everything but not deployed yet

## 📷 Screenshots

Screenshot (925)

Screenshot (923)

Screenshot (924)

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi Review

**Comment by Rayman-Sodhi** [comment]
This branch is 2 commits ahead, 28 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by gurjeetsinghvirdee** [comment]
Merged

**Comment by Rayman-Sodhi** [comment]
This branch is 3 commits ahead, 5 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by gurjeetsinghvirdee** [comment]
Done @Rayman-Sodhi

**Pull request merged**
