### PR TITLE
google keep notes clone (add new clone website)

### PR DESCRIPTION
**Pull request by Ajoe12**
**Google keep notes clone**

**Functionality:**
1. You can add or remove the notes 
2. Used react hooks to change the year mentioned below at footer, will change according to current year
3. The Title hides at the main notes creation at the top

This website is made on react js, so attached a readme and as required a working link has been attached in the Readme.

**Screenshots**
Screenshot 2022-03-03 214837

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
can u make the pr again with latest changes.

**Comment by Rayman-Sodhi** [comment]
u also have to add ur clone details in readme

**Comment by Ajoe12** [comment]
I have added a readme about the project
Is there anything else I had to add in the readme

**Comment by Rayman-Sodhi** [comment]
[](https://user-images.githubusercontent.com/65675692/156740129-604c223a-b1a5-4e86-90ee-610e525095c4.PNG)Capture
kindly add your deployed link in the project readme and also the real website link

**Comment by Ajoe12** [comment]
done...

**Comment by Ajoe12** [comment]
I resolved all the conflicts, plz let me know what is is the issue and I will try to resolve it..

**Pull request merged**
