### PR TITLE
#183 Make My Trip Clone created

### LINKED ISSUE #183: Create Make My Trip Clone
### Is your feature request related to a problem? Please describe.

Yes, this would be on Make My Trip Website

### Describe the solution you'd like.

I will use React 

### Describe alternatives you've considered.

At least use Bootstrap

### Add any other context or screenshots about the feature request here.

image

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
**THIS IS UNDER GSSoC'22**

## 🛠️ Fixes Issue

Closes #183 

## 👨‍💻 Changes proposed
- Create Make My Trip Clone
- Link this clone to index.html
- Update README.md with new clone link

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Nothing specific

## 📷 Screenshots
image

image

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
2 commits behind this repo

**Comment by Kumar-laxmi** [comment]
@gurjeetsinghvirdee I have resolved it, now check please

**Comment by gurjeetsinghvirdee** [comment]
Can you send live link actually I'm on github app so it's not possible to check

**Comment by Kumar-laxmi** [comment]
> Can you send live link actually I'm on github app so it's not possible to check

How do I do that?

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
> > Can you send live link actually I'm on github app so it's not possible to check
> 
> How do I do that?

Forgot about it I checked your live version through your repo

**Comment by gurjeetsinghvirdee** [comment]
This code was copied from `https://github.com/GeekyAnts/mmt-clone-app` @Kumar-laxmi 

@Rayman-Sodhi @whiteHatpro

**Pull request merged**
