### PR TITLE
Added tinder clone

### LINKED ISSUE #256: [Adding]: Building a Tinder Clone
### Description

Building a Tinder Clone web application

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by TG922**
## 🛠️ Fixes Issue

Closes #256 

## 👨‍💻 Changes proposed

- Added tinder clone web application using HTML, CSS, JS

## ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

Image103
Image102

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
This branch is 1 commit ahead, 6 commits behind Rayman-Sodhi/Clone-IT: main
@TG922

**Comment by TG922** [comment]
> This branch is 1 commit ahead, 6 commits behind Rayman-Sodhi/Clone-IT: main @TG922

Ok will send PR again

**Comment by gurjeetsinghvirdee** [comment]
Don't create a PR just fetch your upstream from branch Issue-256

@TG922

**Comment by TG922** [comment]
@gurjeetsinghvirdee Ok will do today ASAP

**Comment by TG922** [comment]
Is it ok @gurjeetsinghvirdee ??

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM

**Pull request merged**
