### PR TITLE
Made Hulu clone

### PR DESCRIPTION
**Pull request by harshit995**

### CODE REVIEW

**Comment by harshit995** [comment]
@Rayman-Sodhi pls accept my pr

**Comment by Rayman-Sodhi** [comment]
Good Job!

**Comment by harshit995** [comment]
@Rayman-Sodhi this is for the SWOC right ?

**Comment by Rayman-Sodhi** [comment]
yes

**Comment by harshit995** [comment]
@Rayman-Sodhi how do we get the points in the google sheet of SWOC that we have contributed in it ??

**Comment by Rayman-Sodhi** [comment]
we update  it  in sheet.I have update ur points

**Pull request merged**
