### PR TITLE
FAQ page created

### LINKED ISSUE #101: Creating a Help and FAQ page
It seems the Help & FAQ page is missing.

The link is given in footer.

So I can create one and link it to it.

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
## 🛠️ Fixes Issue

Closes #101 

## 👨‍💻 Changes proposed
- Creation of completely new page of FAQ
- Linking this FAQ page to index.html

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
There is nothing pertaining to this issue

## 📷 Screenshots
image

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi

**Comment by Kumar-laxmi** [comment]
Is it ok to merge

**Comment by gurjeetsinghvirdee** [comment]
> Is it ok to merge

Actually, PA and mentor will say then I'll merge because am also a contributor & collaborator in this project

**Comment by Rayman-Sodhi** [comment]
please make the request agin after pulling the changes

**Comment by Kumar-laxmi** [comment]
Now please check if it is ok to merge

**Comment by Rayman-Sodhi** [comment]
This branch is 4 commits ahead, 2 commits behind Rayman-Sodhi:main.

**Comment by Kumar-laxmi** [comment]
Is there any merge conflict now?

**Comment by gurjeetsinghvirdee** [comment]
> Is there any merge conflict now?

nope

**Pull request merged**
