### PR TITLE
Added code for youtube clone

### PR DESCRIPTION
**Pull request by anveshajain19**
<h2>What I have used </h2>
<p> HTML </p>
<p>CSS</p>
<p>JS</p>
You can watch it here  
[https://anveshajain19.github.io/YOUTUBE-CLONE/]

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 1 commit ahead, 9 commits behind Rayman-Sodhi:main.

**Comment by Rayman-Sodhi** [comment]
Pull the changes before making a pr 
also add the links in project readme

**Comment by gurjeetsinghvirdee** [comment]
omg 35 conflicts 😴 @anveshajain19 please make pull before making PR

**Comment by anveshajain19** [comment]
> omg 35 conflicts 😴 @anveshajain19 please make pull before making PR

ok

**Pull request merged**
