### PR TITLE
License added

### LINKED ISSUE #122: Project dont have Pull request template

### PR DESCRIPTION
**Pull request by Ash-KODES**
FIXES #122 
FIXES #112

### CODE REVIEW

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Change this file to LICENSE.txt and the copyright owner was Rayman Sodhi so, change the name in this line and year also

`Copyright (c) 2021 Vruksh Ecosystem Foundation`

**Comment by Ash-KODES** [comment]
> Change this file to LICENSE.txt and the copyright owner was Rayman Sodhi so, change the name in this line and year also
> 
> `Copyright (c) 2021 Vruksh Ecosystem Foundation`

Done,but license is meant to be in dot MD(markdown extention),otherwise it wont be showing its effect...correct me if I am wrong?
@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> > Change this file to LICENSE.txt and the copyright owner was Rayman Sodhi so, change the name in this line and year also
> > `Copyright (c) 2021 Vruksh Ecosystem Foundation`
> 
> Done,but license is meant to be in dot MD(markdown extention),otherwise it wont be showing its effect...correct me if I am wrong? @gurjeetsinghvirdee

It will show you effect, ok ignore this file make a new LICENSE.txt file it will show you effect 

I have a same file in my repo leetcode you can checkout their and copy same content here but change the name

**Comment by Ash-KODES** [comment]
> > > Change this file to LICENSE.txt and the copyright owner was Rayman Sodhi so, change the name in this line and year also
> > > `Copyright (c) 2021 Vruksh Ecosystem Foundation`
> > 
> > 
> > Done,but license is meant to be in dot MD(markdown extention),otherwise it wont be showing its effect...correct me if I am wrong? @gurjeetsinghvirdee
> 
> It will show you effect, ok ignore this file make a new LICENSE.txt file it will show you effect
> 
> I have a same file in my repo leetcode you can checkout their and copy same content here but change the name

ok sure

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
