### PR TITLE
Added Starbucks clone

### PR DESCRIPTION
**Pull request by Girlwithasmile**
I've created a clone of everyone's favourite Starbucks Home page. Issue #59  If there are any mistakes, suggestions pls let me know as I am a beginner.
Attached link of drive screen recording of my website
https://drive.google.com/file/d/17C6zH9mEuyHvg7ghPzC7lUWl8C5Hx1UA/view?usp=sharing
previewstarbucks

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
hi please add the links for your project in readme  in the list and also perform a git pull .

**Comment by Rayman-Sodhi** [comment]
this is not correct you have not kept it within table

**Comment by Girlwithasmile** [comment]
Done!
Screenshot 2022-03-09 113639

**Comment by Rayman-Sodhi** [comment]
you have to do it the saME way as strabucks clone not outside table

**Comment by Girlwithasmile** [comment]
I have done the starbucks clone only

**Comment by gurjeetsinghvirdee** [comment]
> I have done the starbucks clone only. I hv created an issue for making the other clones(not made by me) to be in table form in readme.

But you added starbucks in readme then last other rows are effected so if you have to fix it first

**Comment by Girlwithasmile** [comment]
> > I have done the starbucks clone only. I hv created an issue for making the other clones(not made by me) to be in table form in readme.
> 
> But you added starbucks in readme then last other rows are effected so if you have to fix it first

Oh..k done!
Screenshot 2022-03-12 153856

**Pull request merged**
