### PR TITLE
added spotify-clone

### PR DESCRIPTION
**Pull request by anugoyal998**
I have added the **Spotify** clone. Spotify is the world's largest audio streaming platform. The clone uses **Spotify's Web API**. Spotify API restricts some features like play, pause the song to premium users only.
 
**Tech Stack**
- Nextjs
- Recoil
- Spotify Web API
- Beta middleware
- next-auth
- Tailwind CSS

Video Preview: https://youtu.be/f8KouLfCAfM

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
Hi @anugoyal998 please make the request after updating in the readme in section available Clones and also make sure you have added spotify clone in a different folder like other clones .When this is done let me know I will merge it

**Comment by anugoyal998** [comment]
> Hi @anugoyal998 please make the request after updating in the readme in section available Clones and also make sure you have added spotify clone in a different folder like other clones .When this is done let me know I will merge it 
> 

Ok sir, i will do it

**Comment by anugoyal998** [comment]
> Hi @anugoyal998 please make the request after updating in the readme in section available Clones and also make sure you have added spotify clone in a different folder like other clones .When this is done let me know I will merge it

@Rayman-Sodhi I'm getting errors in deploying the spotify clone. But works fine on the local machine.
Screenshot (1333)_LI
So, what to add in the clone output?

**Comment by Rayman-Sodhi** [comment]
it should have the deployed link of the project .u can try deploying on heroku .

**Comment by anugoyal998** [comment]
> it should have the deployed link of the project .u can try deploying on heroku .
> 

Ok i will try to deploy it

**Pull request closed without merging**
