### PR TITLE
Excel Clone recommit

### LINKED ISSUE #462: Microsoft Excel Clone
### Description

Excel Clone.

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by DragonUncaged**
## 🛠️ Fixes Issue

Closes #462 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Demo

### CODE REVIEW

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
image

again converted into binary @DragonUncaged

**Comment by DragonUncaged** [comment]
Done !!

image

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by Rayman-Sodhi** [comment]
This branch is 10 commits ahead, 2 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by DragonUncaged** [comment]
> This branch is 10 commits ahead, 2 commits behind Rayman-Sodhi/Clone-IT:main.

fetch upstream done!!

what else i have to do

**Pull request merged**
