### PR TITLE
Adding Mentor Section and link for repo contributors

### LINKED ISSUE #336: Updating the README.md file with contributor's link for this repo and Adding a section for Mentors
### Is your feature request related to a problem? Please describe.

Yes, the README.md file is very important in any repo so I want to improve it by adding the contributor's link for this repo 

### Describe the solution you'd like.

I wanna add a link to the contributor's link for this repo in the README.md file and also adding a section for Mentors

### Describe alternatives you've considered.

_No response_

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by muhammadgalhoum**
## 🛠️ Fixes Issue

Closes #336 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by muhammadgalhoum** [comment]
Can you please review my pull request @gurjeetsinghvirdee @Rayman-Sodhi @whiteHatpro

**Comment by muhammadgalhoum** [comment]
**Is there exist only one mentor for this project? @gurjeetsinghvirdee**

**Comment by gurjeetsinghvirdee** [comment]
> **Is there exist only one mentor for this project? @gurjeetsinghvirdee**

Bro I do my own so better to add a collaborator not mentors

**Comment by muhammadgalhoum** [comment]
**what is the role of this person @whiteHatpro in this project? @gurjeetsinghvirdee**

**Comment by gurjeetsinghvirdee** [comment]
> **what is the role of this person @whiteHatpro in this project? @gurjeetsinghvirdee**

added as a mentor but offline from the 2nd - 3rd day

**Comment by muhammadgalhoum** [comment]
**please, review this pull request again @gurjeetsinghvirdee**

**Review by gurjeetsinghvirdee — APPROVED** [review]
LGTM💜

**Pull request merged**
