### PR TITLE
Clone linked to site

### LINKED ISSUE #89: Add Facebook and Google Keep Clone to main webste .Link can be found in Readme
Maintain website by adding new clones once pr's are merged ...

### PR DESCRIPTION
**Pull request by gurjeetsinghvirdee**
## 🛠️ Fixes Issue

Closes #89 

## 👨‍💻 Changes proposed
`Airbnb` & `Mac OS`  cloned added to the main site
`Twitter` Clone removed from site bcoz it was Plagiarised Content from this PR #174 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (763)

Screenshot (764)

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
airbne link is pf apple clone .KIndly change it

**Comment by Rayman-Sodhi** [comment]
and there is no image for mac-os

**Comment by gurjeetsinghvirdee** [comment]
> airbnb link is pf apple clone .KIndly change it 

🙄airbnb link working correctly 
Merged PR takes time to deploy 2-3 min 
So now check again it will work fine

**Comment by gurjeetsinghvirdee** [comment]
> and there is no image for mac-os

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi first visit your website if the issues was the same then explain in brief what changes you want

**Comment by Rayman-Sodhi** [comment]
no its fine now.

**Pull request merged**
