### PR TITLE
modify navbar to be more responsive

### LINKED ISSUE #318: Navbar needs modification
### What happened?

Nav links overlap the site's title at some media queries. This is most likely to happen on Ipads since I tested this on a laptop.

Screenshot (308)

### How can we reproduce this bug?

Go to [Clone-IT](https://rayman-sodhi.github.io/Clone-IT/), probably on a laptop.

1. On Firefox browser
    -  press `ctrl + shift + M` to view responsive design.
    -  Choose **iPad Mini** as your device or choose to width of 516

2. On chrome or Brave browser
    - press `ctrl + shift + I`, then `ctrl + shift + M`
    - Choose width of 548

Screenshot (309)_LI

### Desktop Information (Optional)

_No response_

### Urgency (Optional)

_No response_

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
## 👨‍💻 Changes proposed
Make navbar more responsive

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Screenshot (314)
Screenshot (315)
Screenshot (316)

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 1 commit ahead, 3 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by Olaleye-Blessing** [comment]
You can check now @Rayman-Sodhi

**Comment by Rayman-Sodhi** [comment]
This branch is 2 commits ahead, 11 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by Olaleye-Blessing** [comment]
@Rayman-Sodhi check now

**Pull request merged**
