### PR TITLE
PLURALSIGHT WebPage Clone

### PR DESCRIPTION
**Pull request by Mrjoy832**
## 🛠️ Fixes Issue

Closes #
- #166 

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
**All the codes are neat and clean and easy to understand.**

## 📷 Screenshots
**1.Image of Cloned Copy ->**
image
**Video Demo->**

https://user-images.githubusercontent.com/77873383/159204970-229e2fcb-3a10-4db9-85af-47fe840acabb.mp4

**Deployed Link**
https://mrjoy832.github.io/PluralSight_clone/

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee , check the PR of issue #166

**Comment by gurjeetsinghvirdee** [comment]
Deploy it @Mrjoy832 then add link and tech stack in readme file

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by Mrjoy832** [comment]
> Deploy it @Mrjoy832 then add link and tech stack in readme file

Okay

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 deployed link not working

Screenshot (752)

**Comment by Mrjoy832** [comment]
> @Mrjoy832 deployed link not working
> 
> Screenshot (752)
> 
> 

Wait 5 min..I forget to add css file in my repo

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee , updated the link and readme file

**Comment by gurjeetsinghvirdee** [comment]
LGTM💜

**Pull request merged**
