### PR TITLE
Grammarly(Character Counter)

### PR DESCRIPTION
**Pull request by Mrjoy832**
## 🛠️ Fixes Issue

Closes #

- #237 
## 👨‍💻 Changes proposed
- It's a clone of Grammarly with some additional features. I have added the Character count feature into it which shows the typed and remaining characters on the screen and also here is a major feature is that we can copy Text with the button provided.

## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

## Video Demo:

https://user-images.githubusercontent.com/77873383/161383612-fb4a8faf-4476-47ba-af35-2e6486c411af.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
Kindly Check...Hope for a better level this time please 🙃...it will be really motivating .

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 buddy can you deploy this and if possible make responsive then it will goes to label3

**Comment by Mrjoy832** [comment]
> @Mrjoy832 buddy can you deploy this and if possible make responsive then it will goes to label3

okay wait

**Comment by Mrjoy832** [comment]
@gurjeetsinghvirdee  updated deployed link in the readme and its already **responsive** please check

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
