### PR TITLE
Added Reddit Clone

### LINKED ISSUE #645: Reddit Clone
### Description

Want to implement a clone of Reddit. 
Would implement it using just HTML, CSS, Javascript. Rather than using any node_modules for achieving the purpose.

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by hariketsheth**
## 🛠️ Fixes Issue
Fixes #645 

## 👨‍💻 Changes proposed
- Implemented a Reddit Clone, just using HTML, CSS, Javascript

## ✔️ Check List (Check all the applicable boxes) 
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

image

image

### CODE REVIEW

**Comment by hariketsheth** [comment]
## Project Demonstration
https://user-images.githubusercontent.com/72455881/170855074-5bb78dca-3628-420d-b9fc-5bc71ec1cddd.mp4

## Code Demonstration
https://user-images.githubusercontent.com/72455881/170855159-5be522c6-62d8-4bb1-af96-d943e849b36e.mp4

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee @Rayman-Sodhi
Kindly Review this PR.
Thank you !

**Comment by hariketsheth** [comment]
@gurjeetsinghvirdee Missed to add a Level label

**Comment by gurjeetsinghvirdee** [comment]
Sorry itne tabs open rehte h bhul gya me

**Pull request merged**
