### PR TITLE
Fix navigation bar

### LINKED ISSUE #7: Fixing navigation bar of the KFC clone.
Screenshot (1148)
For now, this is what the navigation bar of the actual website looks like and I would like to implement the same in the clone. 
Please review my issue.

### PR DESCRIPTION
**Pull request by arpita221b**
Fixes #7 
Screenshot (1232)

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
sws
@arpita221b  the location and other icons can also be changed to this .

**Comment by arpita221b** [comment]
Hey!
I was thinking of creating a new issue to fix that. If you say so I'll do it in this one.

**Comment by Rayman-Sodhi** [comment]
This comes under navigation only .You can add this in same issue and work on images as a new issue that I have created

**Comment by arpita221b** [comment]
Okay sure, sir!

**Comment by arpita221b** [comment]
I changed it too. Please have a look.
Screenshot (1238)

**Comment by Rayman-Sodhi** [comment]
Did you pull all the changes on the website first?As I merged a request with changes in image section in KFC clone

**Comment by arpita221b** [comment]
Sorry, I didn't do it then but now it's done.

**Pull request merged**
