### PR TITLE
adding images to zara clone

### PR DESCRIPTION
**Pull request by Ashish4321-hub**
Add images to zara clone . there are two images which are not visible ,now i add images .
#429 issue is solved

- [ x] My code follows the code style of this project.
- [ x] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

zara

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
@Rayman-Sodhi can you check this!! (Aisa konsa teer maara h inhone pata ni)

**Comment by Ashish4321-hub** [comment]
Please refer issue no. #429 for details.

**Comment by Ashish4321-hub** [comment]
Before



Screenshot_2022-05-03-10-21-40-47_40deb401b9ffe8e1df2f1cc5ba480b12



After



Screenshot_2022-05-03-16-49-57-07_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by khareyash05** [comment]
@gurjeetsinghvirdee Kindly check the language you are using.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee Kindly check the language you are using.

Acha thk h bhyi sorry me aisehi mjaq karta hu kisi se bhi puch le

**Comment by khareyash05** [comment]
I think this isn't the platform where you should be joking. Kindly joke on your personal groups.This is a professional working environment @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee Hey man! Are you in your senses?

If you have any issues with me then complain it 
Simple

**Comment by khareyash05** [comment]
@gurjeetsinghvirdee An advice - Kindly check if your words are apt for the situation before speaking

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee An advice - Kindly check if your words are apt for the situation before speaking

Sure

**Pull request merged**
