### PR TITLE
Added GitHub homepage clone

### LINKED ISSUE #81: Adding GitHub Homepage Clone
## Idea

Add a Github homepage clone

## Motivation

The project demonstrates the capabilities of flex property in CSS, in addition to a good explanation about how GitHub's frontend is built

### PR DESCRIPTION
**Pull request by XZANATOL**
## Changes

Added Github Homepage Clone

## Issue

fixes #81

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
hi please add the links for your project in readme  in the list and also perform a git pull .

**Comment by XZANATOL** [comment]
@Rayman-Sodhi Done.

**Comment by XZANATOL** [comment]
@Rayman-Sodhi any updates about the review?

**Comment by gurjeetsinghvirdee** [comment]
> @Rayman-Sodhi any updates about the review?

This branch was 4 commit behind, from main branch please fix it then I'll will merge

**Comment by XZANATOL** [comment]
@gurjeetsinghvirdee Done.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
