### PR TITLE
Add a Codepen Clone

### LINKED ISSUE #188: Title: Add a CodePen Clone
### Is your feature request related to a problem? Please describe.

I want to work on adding a Codepen clone to this project.

### Describe the solution you'd like.

I will be using React to build a Codepen clone. Since I will be building from scratch please let me know in how much time should I build it, preferably I require 2-3 weeks.

### Describe alternatives you've considered.

_No response_

### Add any other context or screenshots about the feature request here.

_No response_

### PR DESCRIPTION
**Pull request by mahiiverse1**
## 🛠️ Fixes Issue #188 

Closes #188 

## 👨‍💻 Changes proposed

1. Made a Codepen Clone using React.js 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

codepenclone
codepenclone2

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
Can you plz deploy this @mahiiverse1

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by mahiiverse1** [comment]
Hi! Yes I'm trying to deploy this, Im sorry I couldn't reply and do it
earlier I was actually busy with a project review in my college so really
sorry for the delay. I'll deploy it asap.

**Comment by mahiiverse1** [comment]
@gurjeetsinghvirdee just deployed the website!

**Comment by gurjeetsinghvirdee** [comment]
Loved it✨ @mahiiverse1

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
