### PR TITLE
Add Search Button in Projects Section

### PR DESCRIPTION
**Pull request by zugzwang03**
## 🛠️ Fixes Issue #143 

Closes #143 

## 👨‍💻 Changes proposed
Removed the list of clones, and now on clicking on search icon, the website will be redirected

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
clone

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 6 commits ahead, 3 commits behind Rayman-Sodhi:main.

**Comment by gurjeetsinghvirdee** [comment]
Can you make a video of something how it's working? and upload here! @zugzwang03

**Comment by zugzwang03** [comment]
I updated my fork, and it is up to date with your repository. You can check its working from this website : https://zugzwang03.github.io/Clone-IT/

**Comment by gurjeetsinghvirdee** [comment]
> I updated my fork, and it is up to date with your repository. You can check its working from this website : https://zugzwang03.github.io/Clone-IT/

But it's not working, That's y I ask for video

**Comment by zugzwang03** [comment]
The process is like: I type "Apple Clone" in the search box, and press the search icon, and the apple clone website is redirected to me. Similar thing goes for all other clones, but for any typo, the working will not show. Also, if the input box is blank, the working will not show. Try once again now, if it does not work still, I am trying to make a video.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
Screenshot (744)

Can you change a little bit CSS like changing the width of the search bar and fix it to center or corner that your choice where it looks good @zugzwang03

**Comment by gurjeetsinghvirdee** [comment]
> The process is like: I type "Apple Clone" in the search box, and press the search icon, and the apple clone website is redirected to me. Similar thing goes for all other clones, but for any typo, the working will not show. Also, if the input box is blank, the working will not show. Try once again now, if it does not work still, I am trying to make a video.

yeah it's working, actually, I used it on mobile so I didn't see a search icon no it's working on lappy

**Review by gurjeetsinghvirdee — CHANGES_REQUESTED** [review]
Screenshot (744)

Can you change a little bit CSS like changing the width of the search bar and fix it to center or corner that your choice where it looks good @zugzwang03

**Comment by zugzwang03** [comment]
I tried, but changing the CSS is distorting the layout of the clone boxes placed below. It is better if someone else takes up that issue of making it user responsive in every device.

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
