### PR TITLE
Changed how the search bar is written.

### LINKED ISSUE #186: Fix Search Bar
Sometimes search bar didn't work properly. Umm If I take an example: 
When you search `Apple Clone` and hit the search button that will show you a deployed preview
but when you search `Google Clone` or `Tesla Clone` it doesn't work at all.

### PR DESCRIPTION
**Pull request by laporchen**
Changing from checking with if statements to json for easier way to add
new clone url.

## 🛠️ Fixes Issue

Closes #186 
I think `GOOGLE CLONE` is referring to the `GOOGLE SEARCH ENGINE CLONE`,so I added `GOOGLE CLONE` to open up the same page.
Adds clones that are not in the search bar filter if I did not miss any.
Also changes the way search bar is written. So people in the future will have easier time when adding new clone and url. 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image redirects to YouTube.
[](https://youtu.be/WI8iPJOX6DY)

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
attach screenshots

**Comment by gurjeetsinghvirdee** [comment]
> attach screenshots

Thanks, @Rayman-Sodhi but we have to check search bar is working or not 
attach a video @laporchen

**Comment by laporchen** [comment]
Image redirects to the YouTube video showing `GOOGLE CLONE` and `TESLA CLONE` are working.

**Comment by gurjeetsinghvirdee** [comment]
> Image redirects to the YouTube video showing `GOOGLE CLONE` and `TESLA CLONE` are working.

I mean test your changes in your system record a video and attach it here

**Comment by laporchen** [comment]
https://user-images.githubusercontent.com/31620109/160251851-96cd3927-a694-4cd2-be79-648a9d062953.mov

Last time I tried to attach here and nothing happened. I though it does not work so I uploaded to Youtube.
Re-record the video showing it is indeed my system.

**Comment by gurjeetsinghvirdee** [comment]
> PR-193.mov 
> Last time I tried to attach here and nothing happened. I though it does not work so I uploaded to Youtube. Re-record the video showing it is indeed my system.

Thanks man it looks great 💜

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
