### PR TITLE
added Leetcode Website Clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This is PR of the issue Leetcode Website Clone #407 
Kindly review it sir
Thank you

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
kindly resolve the issues

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi resolved the issues mam

**Comment by Rayman-Sodhi** [comment]
please resolve again

**Comment by Rayman-Sodhi** [comment]
it works sequentially

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi Done mam

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi Please review my PR

**Pull request merged**
