### PR TITLE
add ability to search when enter button is pressed

### LINKED ISSUE #319: Title: pressing enter should search/open project
### Is your feature request related to a problem? Please describe.

I need to take my mouse to the search icon and click on it before my searched project could be opened.

### Describe the solution you'd like.

Pressing `enter button` should open the project if found.

### Describe alternatives you've considered.

_No response_

### Add any other context or screenshots about the feature request here.

Screenshot (310)_LI

The search icon needs to be pressed before a search could be done.

### PR DESCRIPTION
**Pull request by Olaleye-Blessing**
🛠️ Fixes #319 

## 👨‍💻 Changes proposed
Users should be able to search/open a clone when enter button is pressed on the search field.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
This branch is 1 commit ahead, 3 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by Olaleye-Blessing** [comment]
@Rayman-Sodhi that's probably because you merge some requests some hours/minutes ago.

**Comment by Rayman-Sodhi** [comment]
Yes its kind of FIFO .So please resolve the issues

**Comment by Olaleye-Blessing** [comment]
@Rayman-Sodhi you can check now

**Comment by Rayman-Sodhi** [comment]
Too much issues!!  This branch is 2 commits ahead, 11 commits behind Rayman-Sodhi/Clone-IT:main.

**Pull request closed without merging**
