### PR TITLE
Added Discord App Clone

### LINKED ISSUE #116: Add Discord App Page Clone
## Idea

Add a clone of Discord app homepage (the one where we enter to servers & dms)

## Tech Stack

- [x] HTML
- [x] CSS
- [x] JS
- [x] Bootstrap 5

Issue created under GSSoC'22 contributions

### PR DESCRIPTION
**Pull request by XZANATOL**
## 🛠️ Fixes Issue

Closes #116 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

image

PR made under GSSoC'22 contributions.

### CODE REVIEW

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Comment by gurjeetsinghvirdee** [comment]
LGTM ✨

**Comment by XZANATOL** [comment]
@gurjeetsinghvirdee May I get the level label assigned on the PR?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee May I get the level label assigned on the PR?

Is their any deployed link of your project? if you have then add in readme 

Level will be decided on the basis of your work

**Comment by gurjeetsinghvirdee** [comment]
@XZANATOL make changes and create new PR mentioning issue and last PR no.

**Comment by XZANATOL** [comment]
I think you mean this?
https://htmlpreview.github.io/?https://github.com/XZANATOL/Clone-IT/blob/Discord_Clone/Discord_App_Clone/home.html

**Comment by gurjeetsinghvirdee** [comment]
> I think you mean this? https://htmlpreview.github.io/?https://github.com/XZANATOL/Clone-IT/blob/Discord_Clone/Discord_App_Clone/home.html

yeah add this link in readme with the official link and tech stacks you used

**Pull request merged**
