### PR TITLE
spacex-page

### LINKED ISSUE #311: Spacex Landing page clone:
### Description

This is a simple clone of spacex.com webpage made with HTML,CSS & JS which is fully responsive.

Contribution made as a GSSOC'22 participant.

spacex

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rayman-Sodhi/Clone-IT#Contribution-Guidelines) of this project.

### PR DESCRIPTION
**Pull request by VaibhavUpreti**
## 🛠️ Fixes Issue
Closes #311 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Contribution under GSSOC'22

## 📷 Screenshots
spacex

### CODE REVIEW

**Comment by gurjeetsinghvirdee** [comment]
buddy @VaibhavUpreti deploy this

**Comment by VaibhavUpreti** [comment]
Deployed at 

https://vaibhavupreti.github.io/spacex-static/

**Comment by gurjeetsinghvirdee** [comment]
@VaibhavUpreti resolve conflicts

**Comment by VaibhavUpreti** [comment]
@gurjeetsinghvirdee ig this should resolve the conflicts.

**Pull request merged**
