### PR TITLE
Added Hackerearth clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This is the PR of the issue  HackerEarth Website Clone #406
Kindly review it sir 
Thank you

### CODE REVIEW

**Comment by Rayman-Sodhi** [comment]
kindly resolve the issues

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi Resolved the issues mam

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi Please review my PR

**Comment by Rayman-Sodhi** [comment]
This branch is 4 commits ahead, 5 commits behind Rayman-Sodhi/Clone-IT:main.

**Comment by SupriyaGembali** [comment]
@Rayman-Sodhi  Done mam

**Comment by whiteHatpro** [comment]
@SupriyaGembali add the ss and the video of the site

**Comment by SupriyaGembali** [comment]
ss and videos of site:
image


https://user-images.githubusercontent.com/94470209/165733922-da6486a4-b207-438e-852a-0eb38fb06d53.mp4

**Comment by SupriyaGembali** [comment]
@whiteHatpro Added Screenshot, Video Please review

**Comment by SupriyaGembali** [comment]
@gurjeetsinghvirdee Please review my PR

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee Please review my PR

I will review but can you give a reply for your different merged PRs, show us a proof that you make projects fro your academics

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
