### PR TITLE
added more websites in the cloneit website

### PR DESCRIPTION
**Pull request by VaibhavUpreti**
## 🛠️ Fixes Issue #355 

Closes #

## 👨‍💻 Changes proposed
Added 3 websites 
- pinterest
- zara
- wikipedia UI

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Many clone websites are not hosted like
- zoom clone 
- whatsapp ui
- windows 11

## 📷 Screenshots
Screenshot 2022-04-16 at 8 06 27 PM

### CODE REVIEW

**Comment by VaibhavUpreti** [comment]
I also removed my spacex clone which was added by someone else who created the issue first.

**Comment by VaibhavUpreti** [comment]
@gurjeetsinghvirdee I have manually hosted these websites on netlify..... 
like
windows 11 - https://magical-wisp-ca980c.netlify.app/
whatsapp - https://whatsapp-ui-static.netlify.app/

I can add the missing projects..... will do in an hour or so

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I have manually hosted these websites on netlify..... 
> like
> windows 11 - https://magical-wisp-ca980c.netlify.app/
> whatsapp - https://whatsapp-ui-static.netlify.app/
> 
> I can add the missing projects..... will do in an hour or so

Windows 11 link not working

**Comment by VaibhavUpreti** [comment]
Oops I changed the domain name and added the older one 

here u go https://windows-11-static.netlify.app/

**Review by gurjeetsinghvirdee — APPROVED** [review]

**Pull request merged**
